name = "Hypertransform"
uuid = "fc0ce2b4-e141-4471-8aec-392ceb78b612"
authors = ["Riccardo Buscicchio <riccardo.buscicchio@unimib.it> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
