name = "Hypertransform"
uuid = "fc0ce2b4-e141-4471-8aec-392ceb78b612"
authors = ["Riccardo Buscicchio <riccardo.buscicchio@unimib.it> and contributors"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.17"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
